### ISSUE TITLE
Using Docker Compose setting user, password and database name using environment variable fails

### ISSUE THREAD

**Issue by erwagasore** [kiasaki/docker-alpine-postgres#18]
Using `docker run ....` with environment variable everything works perfectly

```bash
$ d run -d -name foo -it -e 'POSTGES_USER=foo' -e 'POSTGRES_PASSWORD=foobar' -e 'POSTGRES_DB=baz'

$ d exec -it foo psql -U foo baz
psql (9.4.6, server 9.5.2)
WARNING: psql major version 9.4, server major version 9.5.
         Some psql features might not work.
Type "help" for help.

baz=# 
```

I prefer using docker compose to run many containers
Here is a portion of `docker-compose.yml' file

```yaml
version: '2'

services:
  postgres:
    restart: always
    image: kiasaki/alpine-postgres:9.5
    environment:
      - POSTGRES_USER:'foo'
      - POSTGRES_PASSWORD:'foobar'
      - POSTGRES_DB:'baz'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
```
When I try to execute psql command into the new container environment variables are not recognized

```bash
$ d exec -it foo psql -U foo baz
psql: FATAL:  role "foo" does not exist
```

Is there something I am doing wrong? Need your help. Thanks
