### ISSUE TITLE
Postgres startup with specified username and password throws

### ISSUE THREAD

**Issue by hsaraogi** [kiasaki/docker-alpine-postgres#32]
```
postgres_1  | PostgreSQL stand-alone backend 9.6.2
postgres_1  | backend> statement: CREATE DATABASE atlas;
postgres_1  |
postgres_1  | backend>
postgres_1  |
postgres_1  | PostgreSQL stand-alone backend 9.6.2
postgres_1  | backend> statement: CREATE USER palantir WITH SUPERUSER PASSWORD 'palantir';
postgres_1  |
postgres_1  | backend>
postgres_1  | waiting for server to start....FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
postgres_1  | LOG:  database system is shut down
postgres_1  | pg_ctl: could not start server
postgres_1  | Examine the log output.
postgres_1  |  stopped waiting
```

This does not happen on the 9.5 image but does on the latest image. Here's my docker-compose:

```
version: '2'

services:
  postgres:
    image: kiasaki/alpine-postgres
    environment:
       POSTGRES_PASSWORD: palantir
       POSTGRES_USER: palantir
       POSTGRES_DB: atlas
    ports:
      - "5432"
```

In AtlasDB, we are sticking to the version 9.5 for now [Pull request](https://github.com/palantir/atlasdb/pull/1897).
