### ISSUE TITLE
Fatal error with latest update

### ISSUE THREAD

**Issue by khorolets** [kiasaki/docker-alpine-postgres#33]
Hi! Thanks for your image, I'm happy using it!

Unfortunately, with the latest update, I'm not able to run postgres in `docker-compose.yml`

The error is

```
FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
```

Your image part from `docker-compose.yml`

```yaml
postgres:
  restart: always
  image: kiasaki/alpine-postgres:latest
  environment:
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=test_db
    - POSTGRES_USER=test_user
  volumes:
    - ./persistant/pgdata:/var/lib/postgresql/data
```

I've switched to `9.5` tag and everything works fine.
